### ISSUE TITLE
Fails on non Windows platforms

### ISSUE THREAD

**Issue by X123M3-256** [oli414/Blender-RCT-Graphics#12]
The default file path to the palette and output directories includes backslashes, which some platforms treat as an escape character, not a directory separator. It works if you change the default paths, but as the error message doesn't say why it failed, it's not obvious that you have to do this.

[These functions](https://docs.python.org/3.4/library/os.path.html) may help with handling paths in a platform independent manner.

**Comment by oli414** [comment]
The latest update should work cross-platform (in theory). I'll keep this open until that has been verified

**Comment by I-R** [comment]
Hi, thanks for your work!

unfortunately, the error still persists:
```
/bin/sh: 1: Syntax error: word unexpected (expecting ")")
Traceback (most recent call last):
  File "/home/reimann/.config/blender/2.79/scripts/addons/rct-graphics-helper/operators/render_operator.py", line 80, in execute
    render_task_processor.process(task, finish)
  File "/home/reimann/.config/blender/2.79/scripts/addons/rct-graphics-helper/processors/render_task_processor.py", line 61, in process
    self._step(task_process_context)
  File "/home/reimann/.config/blender/2.79/scripts/addons/rct-graphics-helper/processors/render_task_processor.py", line 81, in _step
    current_process.process(current_frame, frame_process_callback)
  File "/home/reimann/.config/blender/2.79/scripts/addons/rct-graphics-helper/processors/frame_processors/merge_masks_processor.py", line 61, in process
    self.renderer.magick_path, main_meta_output), shell=True))
  File "/snap/blender/20/2.79/python/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/snap/blender/20/2.79/python/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'magick ( "/home/reimann/Blender/Blender-RCT-Graphics-master/output/.temp/meta_render_0_aa__0000.exr" -channel Green,Blue -evaluate set 0 +channel ) ( "/home/reimann/Blender/Blender-RCT-Graphics-master/output/.temp/meta_render_0_naa__0000.exr" ) -compose CopyOpacity -composite "/home/reimann/Blender/Blender-RCT-Graphics-master/output/.temp/meta_render_0.mpc"' returned non-zero exit status 2
```
You need to escape the "(" in the magick commands -> "\("

**Comment by oli414** [comment]
Thanks for checking! 

I've tried to escape them, but then the command breaks on Windows annoyingly! I need to figure out a way to make this work on both linux and windows

**Comment by Ryder17z** [comment]
There's probably a way to check what the current OS is and then change
things accordingly

**Comment by I-R** [comment]
Hi, just sent a pull request ;)
